
name: dbt CI

on:
  push:
    branches:
      - main

jobs:
  dbt-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dbt
        run: pip install dbt-snowflake

      - name: Install dbt packages
        working-directory: snowflake_dbt_project
        run: dbt deps

      - name: Check dbt version
        run: dbt --version

      - name: dbt compile
        working-directory: snowflake_dbt_project
        run: dbt compile
